### ISSUE TITLE
Unable to start the server

### ISSUE THREAD

**Issue by svedbg** [portableutm/dronfiesuss#12]
Using `npm start` the project `dronfiesuss` is not starting and throwing exception.

I have following `.env` file created in main dir

```
PORT=3000
DATABASE_CONNECTION_NAME=dev

JWTSECRET=xxxxxxxxxxxx
JWT_EXPIRATION_TIME=1h

SMTP_URL=localhost
SMTP_USERNAME=admin@sved.net
SMTP_PASSWORD=xxxxxxxxxxxx
SMTP_PORT=587
SMTP_SECURE=false
SMTP_SELF_SIGNED=true

ADMIN_EMAIL=admin@sved.net

FRONT_END_URL=https://localhost/
BACKEND_URL=https://localhost:3000/

TEST_TIMEOUT=5000
```

the orm config looks as follow and is placed in main folder - `ormconfig.json`

```
[{
   "name": "dev",
   "type": "postgres",
   "host": "localhost",
   "port": 5432,
   "username": "dev_user",
   "password": "xxx",
   "database": "dev",
   "synchronize": true,
   "dropSchema": true,
   "logging": false,
   "entities": [
      "src/entities/**/*.ts"
   ],
   "migrations": [
      "src/migration/**/*.ts"
   ],
   "subscribers": [
      "src/subscriber/**/*.ts"
   ],
   "cli": {
      "entitiesDir": "src/entities",
      "migrationsDir": "src/migration",
      "subscribersDir": "src/subscriber"
   }
}
]
```

Here is the log when it's started:
```
[utmadmin@fedora dronfiesuss]$ npm start

> DronfiesUSS@0.1.0 start /opt/dronfiesuss
> ts-node src/index.ts

Constructor-> port:3000 connName:dev
Path to save upload files::/opt/dronfiesuss/src/uploads
Connection name #dev#!
RangeError [ERR_SOCKET_BAD_PORT] [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at validatePort (internal/validators.js:211:11)
    at Server.listen (net.js:1444:5)
    at App.listen (/opt/dronfiesuss/src/app.ts:217:21)
    at Object.<anonymous> (/opt/dronfiesuss/src/index.ts:7:9)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/opt/dronfiesuss/node_modules/ts-node/src/index.ts:392:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/opt/dronfiesuss/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DronfiesUSS@0.1.0 start: `ts-node src/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DronfiesUSS@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/utmadmin/.npm/_logs/2021-05-25T08_44_04_535Z-debug.log
****
```

**Comment by svedbg** [comment]
There is undocumented HTTP_PORT property which needs to be set in .env. It's not specified in sample.env file.
